Allow 'service_account_key' to contain either the path to or the content of a key file
hanneshayashi/terraform-provider-gdrive pull request #5
Opened 2021-08-18 12:48 UTC by michael-richard-3r

2021-08-18 15:06 UTC, hanneshayashi requested changes
Thanks for the MR. This seems like a reasonable change and I'd be happy to pull it in. One small thing that you could change: I think we should first try to open the file and only if that fails pass the value to the auth function, in the hope that it is a valid key, in order to avoid filling the slice twice most of the time.

2021-08-18 15:39 UTC, michael-richard-3r commented
I don't disagree. In fact, I was thinking that maybe we should check if the variable is valid json and if not, we check if we can open the file. What do you think?

2021-08-18 17:57 UTC, hanneshayashi commented
Sounds good. I suppose https://pkg.go.dev/encoding/json#Valid should do the
trick.

2021年8月18日(水) 17:39 Michael Richard ***@***.***>:

> I don't disagree. In fact, I was thinking that maybe we should check if
> the variable is valid json and if not, we check if we can open the file.
> What do you think?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/hanneshayashi/terraform-provider-gdrive/pull/5#issuecomment-901219555>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGKXII3XAN6QHLB7L2PYTB3T5PH45ANCNFSM5CL7E2BA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-19 05:27 UTC, merged

2021-08-19 06:47 UTC, hanneshayashi commented
Released with v0.5.0